// Generated by IcedCoffeeScript 108.0.11
(function() {
  "use strict";
  moment.locale('zh-cn');

  $(function() {
    if ($) {
      if ($.fn.iCheck) {
        $("input:checkbox, input:radio").iCheck({
          checkboxClass: "icheckbox_minimal",
          radioClass: "iradio_minimal",
          increaseArea: "20%"
        });
      }
      if ($.fn.slimScroll) {
        $('.slim-scroll').each(function() {
          return $(this).slimScroll({
            height: $(this).height()
          });
        });
      }
    }
    if (typeof dialog !== "undefined") {
      dialog.set({
        title: "INFO",
        shade: [0.2, "#000"],
        shadeClose: false,
        shift: 0,
        maxmin: true,
        fix: true,
        btn: ["OK", "Cancel"],
        closeBtn: 1,
        tips: [1, '#f0ad4e'],
        tipsTime: 3000,
        loadingIcon: 1,
        loadingShade: [0.6, "#fff"],
        useAlertify: true
      });
    }
    $("form.readonly").find("input,select,button").each(function() {
      var tag, tagType, val, wrapper;
      tag = $(this)[0].tagName;
      tagType = $(this).attr("type");
      val = "";
      switch (tag) {
        case "INPUT":
          $(this).attr("readonly", true);
          $(this).attr("disabled", true);
          switch (tagType) {
            case "radio":
            case "checkbox":
              wrapper = $(this).parent();
              if (wrapper.parent().hasClass("checkbox" || wrapper.parent().hasClass("radio"))) {
                wrapper = wrapper.parent();
              }
              if ($(this).is(":checked")) {
                val = wrapper.text();
                wrapper.after("<div class='form-control-static'>" + val + "</div>");
              }
              return wrapper.remove();
            case "file":
              wrapper = $(this).parents('.form-group');
              return wrapper.remove();
            default:
              val = $(this).val();
              $(this).after("<div class='form-control-static'>" + val + "</div>");
              return $(this).remove();
          }
          break;
        case "SELECT":
          val = $(this).val();
          $(this).after("<div class='form-control-static'>" + val + "</div>");
          return $(this).remove();
      }
    });
    $("form.readonly:not(:visible)").show();
  });

}).call(this);
