// Generated by IcedCoffeeScript 108.0.11
(function() {
  QUnit.test("mergeUrl", (function(_this) {
    return function(assert) {
      var check;
      check = function(root, relative, result) {
        return assert.equal(mergeUrl(root, relative), result, "" + root + " | " + relative + " => " + result);
      };
      check("http://www.bndy.net/root/sub/index.html", "detail.html", "http://www.bndy.net/root/sub/detail.html");
      check("http://www.bndy.net/root/sub/index.html", "/detail.html", "http://www.bndy.net/detail.html");
      check("http://www.bndy.net/root/sub/index.html", "../detail.html", "http://www.bndy.net/root/detail.html");
      check("http://www.bndy.net/root/sub/index.html", "../../detail.html", "http://www.bndy.net/detail.html");
      return check("http://www.bndy.net/root/sub/index.html", "http://www.bndy.net/detail.html", "http://www.bndy.net/detail.html");
    };
  })(this));

  QUnit.test("setUrl", (function(_this) {
    return function(assert) {
      var check, checkLocal;
      checkLocal = function(key, value, result) {
        return assert.ok(setUrl(key, value).indexOf(result) > 0, "" + key + " | " + value + " => " + (setUrl(key, value)));
      };
      check = function(url, key, value, result) {
        return assert.equal(setUrl(url, key, value), result, "" + url + " | " + key + " | " + value + " => " + (setUrl(url, key, value)));
      };
      checkLocal("page", 3, "page=3");
      check("http://www.bndy.net/index", "page", 3, "http://www.bndy.net/index?page=3");
      check("http://www.bndy.net/index?page=1", "page", 3, "http://www.bndy.net/index?page=3");
      check("http://www.bndy.net/index?k=bndy&page=1", "page", 3, "http://www.bndy.net/index?k=bndy&page=3");
      return check("http://www.bndy.net/index?page=1&k=bndy", "page", 3, "http://www.bndy.net/index?page=3&k=bndy");
    };
  })(this));

}).call(this);
